# Generated by Django 3.2 on 2022-10-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_degital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_degital',
            new_name='is_digital',
        ),
    ]
