# Generated by Django 3.2 on 2022-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_is_degital_product_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
