# Generated by Django 3.2 on 2022-10-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_is_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='products/')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_file', to='products.product')),
            ],
        ),
    ]
