# Generated by Django 3.2 on 2022-10-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
