# Generated by Django 3.2 on 2022-10-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20221025_0716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
    ]
